// Real Gmail draft creation.

import { google } from "googleapis";
import { authorizedClient } from "./oauth";

export interface DraftResult {
  mode: "real" | "simulated";
  link: string | null;
  summary: string;
}

/**
 * Creates a real Gmail draft when connected; otherwise returns a simulated
 * result so the flow completes. The draft body is generated by the agent.
 */
export async function createGmailDraft(
  origin: string,
  args: { to?: string; subject: string; body: string },
): Promise<DraftResult> {
  const client = authorizedClient(origin);

  if (!client) {
    return {
      mode: "simulated",
      link: null,
      summary: `Would draft email "${args.subject}" (connect Gmail to make it real).`,
    };
  }

  const gmail = google.gmail({ version: "v1", auth: client });
  const raw = buildRawMessage(args);
  const res = await gmail.users.drafts.create({
    userId: "me",
    requestBody: { message: { raw } },
  });

  const draftId = res.data.id;
  return {
    mode: "real",
    link: draftId ? `https://mail.google.com/mail/u/0/#drafts` : null,
    summary: `Drafted email "${args.subject}" — ready in your Gmail drafts to review and send.`,
  };
}

function buildRawMessage(args: {
  to?: string;
  subject: string;
  body: string;
}): string {
  const lines = [
    args.to ? `To: ${args.to}` : "",
    `Subject: ${args.subject}`,
    "Content-Type: text/plain; charset=utf-8",
    "",
    args.body,
  ].filter(Boolean);
  const message = lines.join("\r\n");
  // base64url encode
  return Buffer.from(message)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}
